apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: first-pvc
  namespace: application-one
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
